---
language: nix

matrix:
  include:
    - os: osx
    - os: linux

before_install:
  # Clone nonlibc repo as we depend on it but it hasn't been added to nixpkgs
  # TODO: replace this with a nix-channel instead of a download
  - |
    pushd ~
    git clone https://github.com/siriobalmelli/nonlibc.git
    popd

script:
  - |
    if ! nix-build -I ~; then
        echo "build fail! nix-info follows" >&2
        nix-shell -p nix-info --run "nix-info -m"
        exit 1
    fi
...
